Controllers/DividirController.cs
using Microsoft.AspNetCore.Mvc;
using iTextSharp.text.pdf;
using iTextSharp.text;
using SimplePDF.Models;
using System.IO.Compression;

namespace SimplePDF.Controllers
{
    public class DividirController : Controller
    {
        public static string nomePasta = "";
        public static String resource;
        public string PastaDestino = "";
        private readonly IWebHostEnvironment _web;
        
        public IActionResult Index()
        {
            return View();
        }

        public DividirController(IWebHostEnvironment web)
        {
            nomePasta = ControlePastas.GeraNomePasta();
            _web = web;
            PastaDestino = Path.Combine(_web.WebRootPath + @"\Arquivos\Dividir\" + nomePasta);
        }

       public IActionResult Download()
        {
            return View();
        }

        public IActionResult DividirPDF()
        {
            Dividir.dividindo = "";
            return View();
        }

           
        [HttpPost]
        public async Task<IActionResult> DividirPDF(IFormFile[] filesupload, int pagInicio, int pagFim)
        {
            var pastaDownload = ControlePastas.GeraNomePasta();
            if (filesupload == null || filesupload.Length == 0)
        {
            ViewData["Message"] = "Selecione o arquivo!";
                return View();
        }
        else
        {
            Directory.CreateDirectory(PastaDestino);
                
                foreach (IFormFile file in filesupload)
                {

                    var savefile = Path.Combine(PastaDestino, "upload.pdf");
                    {
                        var fileselected = new FileStream(savefile, FileMode.Create);
                        await file.CopyToAsync(fileselected);
                        ViewData["Message"] = "Mensagem sucesso";
                        fileselected.Close();
                    }
                resource = file.FileName;
                }


                ExtraiPagina(pagInicio, pagFim);
               
                Directory.CreateDirectory(Path.Combine(_web.WebRootPath , @"Arquivos" , @"Download", pastaDownload));
                ZipFile.CreateFromDirectory(PastaDestino, Path.Combine(_web.WebRootPath, @"Arquivos" ,@"Download",pastaDownload, @"Arquivo.zip"));
            }
            
            Dividir.nomeArquivo = @"../Arquivos/Download/" + pastaDownload + @"/Arquivo.zip";
            Dividir.dividindo = "http-equiv=refresh";
            
            return Download();
        }


        


        public void ExtraiPagina(int pagInicio, int pagFim)
        {
            
            PdfReader pdfReader = new PdfReader(PastaDestino+ @"\" + @"upload.pdf");
            
            Document document = new Document();
            

            if (pdfReader.NumberOfPages > 0)
            {
                if ((pagInicio != 0) && (pagFim != 0))
                {
                    for (int i = 1; i <= pdfReader.NumberOfPages; i++)
                    {
                        if ((i >= pagInicio) && (i <= pagFim))
                        {
                            PdfCopy pdfCopy = new PdfCopy(document, new FileStream(Path.Combine(PastaDestino, string.Format("Pagina_{0}.pdf", i)), FileMode.Create));
                            document.Open();
                            pdfCopy.AddPage(pdfCopy.GetImportedPage(pdfReader, i));
                        }
                    }
                }
                else
                {
                    for (int i = 1; i <= pdfReader.NumberOfPages; i++)
                    {
                        
                            PdfCopy pdfCopy = new PdfCopy(document, new FileStream(Path.Combine(PastaDestino, string.Format("Pagina_{0}.pdf", i)), FileMode.Create));
                            document.Open();
                            pdfCopy.AddPage(pdfCopy.GetImportedPage(pdfReader, i));
                        
                    }
                }
                document.Close();
            }
            else
            {
                return;
            }
                
        }

    }
}

Controllers/JuntarController.cs
using Microsoft.AspNetCore.Mvc;
using iText.Kernel.Pdf;
using PdfDocument = iText.Kernel.Pdf.PdfDocument;
using iText.Kernel.Utils;
using SimplePDF.Models;

namespace SimplePDF.Controllers
{

    public class JuntarController : Controller
    {
        private readonly IWebHostEnvironment _web;
        public static string nomePasta = "";
        public string PastaDestino = "";
     
        
        public JuntarController(IWebHostEnvironment web)
        {
            nomePasta = ControlePastas.GeraNomePasta();
            _web = web;
            PastaDestino = Path.Combine(_web.WebRootPath + @"\Arquivos\Juntar\" + nomePasta);
            
        }
        public IActionResult JuntarPDF()
        {
            Juntar.juntando = "";
            
            return View();
        }
        public IActionResult Download()
        {

            return View();
        }
        public IActionResult Juntando()
        {

            return View();
        }

        
       

        [HttpPost]
        public async Task<IActionResult> JuntarPDF(IFormFile[] filesupload)
        {
            var numArquivo = 0;
            if(filesupload == null || filesupload.Length == 0)
            {
                ViewData["Message"] = "Selecione os arquivos!";
                return View();
            }
            else
            {
                Directory.CreateDirectory(PastaDestino);
                    foreach(IFormFile file in filesupload)
                    {
                    numArquivo = numArquivo + 1;
                    var savefile = Path.Combine(PastaDestino, @"pagina"+numArquivo);
                    {
                        var fileselected = new FileStream(savefile, FileMode.Create);
                        await file.CopyToAsync(fileselected);
                        ViewData["Message"] = "Mensagem sucesso";
                        fileselected.Close();
                    }
                    
                }
            }
            
            carregaArquivos();
            Juntar.nomeArquivo = @"../Arquivos/Juntar/" + nomePasta + @"/merged.pdf";
            Juntar.juntando = "http-equiv=refresh";
          
            return Download();
        }

        public void carregaArquivos()
        {
            
            var path = PastaDestino;
            var arquivos = GetFiles(path);
            var src0 = System.IO.Path.Combine(path, "merged.pdf");
            var wtr0 = new PdfWriter(src0);
            var pdf0 = new iText.Kernel.Pdf.PdfDocument(wtr0);
            var merger = new PdfMerger(pdf0);
            foreach (string arquivo in arquivos)
            {            

            var src1 = arquivo;
            var fi1 = new FileInfo(src1);
            var rdr1 = new iText.Kernel.Pdf.PdfReader(fi1);
            var pdf1 = new PdfDocument(rdr1);

            merger.Merge(pdf1, 1, pdf1.GetNumberOfPages());
            


            }
            merger.Close();
            pdf0.Close();

        }

        private string[] GetFiles(string caminho)
        {
            return Directory.GetFiles(caminho, "*.*", SearchOption.TopDirectoryOnly);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UsaPDF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SimplePDF.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="navegacao">
        <nav  class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3">
            <div  class="container-fluid">
                <a class="navbar-brand" style="color: #000000;" asp-area="" asp-controller="Home" asp-action="Index">UsaPDF</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" style="color: #000000;" asp-area="" asp-controller="Juntar" asp-action="JuntarPDF">Juntar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: #000000;" asp-area="" asp-controller="Dividir" asp-action="DividirPDF">Dividir</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
           
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>